#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 06 09:27:34 CET 2023
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cod5_top_func_synth -key {Post-Synthesis:sim_1:Functional:cod5_top} -tclbatch cod5_top.tcl -log simulate.log"
xsim cod5_top_func_synth -key {Post-Synthesis:sim_1:Functional:cod5_top} -tclbatch cod5_top.tcl -log simulate.log

